web: bench serve --port 8000
socketio: node socketio.js
schedule: bench schedule
worker_default: bench worker --queue default
worker_short: bench worker --queue short
worker_long: bench worker --queue long 